/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.106
 * Generated at: 2020-12-08 13:19:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Practice33;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 컴퓨터학과 20190941 김경민 -->\r\n");
      out.write("<!-- 최적 실행화면 : Chrome browser -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>회원 가입</title>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\ttd.center{\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ttd.color{\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tbackground-color: #FFDAB9;\r\n");
      out.write("\t\t\t\theight: 50px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ttd.form{\r\n");
      out.write("\t\t\t\tborder: solid 1px #000000;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ttable.form{\r\n");
      out.write("\t\t\t\tborder-collapse: collapse;\r\n");
      out.write("\t\t\t\tborder: solid 1px #000000;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ttd.title{\r\n");
      out.write("\t\t\t\tborder: solid 1px #000000;\r\n");
      out.write("\t\t\t\tbackground-color: #ECECEC;\r\n");
      out.write("\t\t\t\tfont-weight: bold; \r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tinput.imageAlign{\r\n");
      out.write("\t\t\t\tvertical-align:middle;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tfunction checkEmail() {\r\n");
      out.write("\t\t\t\tvar txtMail = frm3.email.value;\r\n");
      out.write("\t\t\t\tvar result = txtMail.indexOf(\"@\");\r\n");
      out.write("\t\t\t\tif(result == -1){\r\n");
      out.write("\t\t\t\t\talert('이메일주소 형식이 틀렸습니다.');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\talert('사용가능한 이메일 주소입니다.');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tclearMessage();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction clearMessage(){\r\n");
      out.write("\t\t\t\tfrm3.email.value=\"\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"center\"><img src=\"image/eclass_title.jpg\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<form name=\"frm3\" action=\"register.jsp\">\r\n");
      out.write("\t\t\t<table class=\"form\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" class=title>회원 가입</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"title\">아이디</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"form\"><input type=\"text\" name=\"id\"> <input type=\"image\" src=\"image/check.gif\" class=\"imageAlign\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"title\">패스워드</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"form\"><input type=\"password\" name=\"pw\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"title\">성별</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"form\"><input type=\"radio\" name=\"gen\" value=\"1\" name=\"gender\">남 <input type=\"radio\" name=\"gen\" value=\"2\" name=\"gender\" checked>여</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"title\">국적</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"form\"><input type=\"text\" readonly value=\"대한민국\"> <input type=\"button\" value=\"국적변경\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"title\">휴대폰</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t <select name=\"phone\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\" selected>010</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">011</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">017</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">070</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">080</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t - <input type=\"text\" size=\"5px\"> - <input type=\"text\" size=\"5px\"> \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"title\">이메일</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"form\"><input type=\"text\" size=\"40px\" value=\"소식지 받아보기\" name=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonFocus=\"this.value='' \" name=\"email\">\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" src=\"image/check.gif\" class=\"imageAlign\" onClick=\"checkEmail()\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"title\">생일</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"form\"><input type=\"date\" name=\"birth\" value=\"연도-월-일\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"title\">관심분야</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"form\"><input type=\"checkbox\" name=\"hobby\" value=\"0\">뉴스 \r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"hobby\" value=\"1\" checked>맛집\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"hobby\" value=\"2\">책 \r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"hobby\" value=\"3\">영화 \r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"hobby\" value=\"4\">여행\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"title\">가입인사</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"form\"><textarea cols=\"60px\" rows=\"10px\">회원들에게 간단한 가입인사를 남겨주세요</textarea></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"title\">증명사진</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"form\"><input type=\"file\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t \t<td colspan=\"2\" class=\"title\">\r\n");
      out.write("\t\t\t\t \t<input type=\"submit\" value=\"가입하기\"> <input type=\"reset\" value=\"다시작성\">\r\n");
      out.write("\t\t\t\t \t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
