/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.106
 * Generated at: 2020-12-03 14:49:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Index</title>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tbackground-color: #f5f5f5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div {\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("\tmargin-right: auto;\r\n");
      out.write("\tmargin-top: 15px;\r\n");
      out.write("\tpadding-top: 30px;\r\n");
      out.write("\tpadding-left: 15px;\r\n");
      out.write("\tpadding-right: 15px;\r\n");
      out.write("\tpadding-bottom: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1, h2 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1, h2, hr, ul {\r\n");
      out.write("\tbackground-color: white\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("\twidth: 70px;\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tborder: 1px solid gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tmargin-top: 70px;\r\n");
      out.write("\tpadding-right: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li {\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tpadding-top: 35px;\r\n");
      out.write("\tpadding-bottom: 35px;\r\n");
      out.write("\tborder-bottom: 1px solid gray;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h2>웹프로그래밍 프로젝트(1-16조)</h2>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<h1>Index</h1>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>Problem_01: 주소록\r\n");
      out.write("\t\t\t\t<button type=button\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='Problem_01/addr_list.jsp'\">link</button>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>Problem_02: 달력\r\n");
      out.write("\t\t\t\t<button type=button\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='Problem_02/calendar.jsp'\">link</button>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>Problem_03: 시간표\r\n");
      out.write("\t\t\t\t<button type=button\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='Problem_03/Problem_03.jsp'\">link</button>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
