/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.106
 * Generated at: 2020-10-09 09:15:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Practice12;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class include_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Practice12/news.jsp", Long.valueOf(1602234855959L));
    _jspx_dependants.put("/Practice12/calendar.jsp", Long.valueOf(1602234905822L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Practice 12</title>\r\n");
      out.write("<style>\r\n");
      out.write("  \tth, td {\r\n");
      out.write("    \ttext-align: center;\r\n");
      out.write("  \t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<h2>include 지시어 연습</h2>\r\n");
      out.write("<hr>\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("\ttable.cal {\r\n");
      out.write("\t\twidth: 270px;\r\n");
      out.write("\t    height: 200px;\r\n");
      out.write("\t    border: 1px solid black;\r\n");
      out.write("\t    border-collapse: collapse;\r\n");
      out.write("  \t}\r\n");
      out.write("  \tth.cal, td.cal {\r\n");
      out.write("    \tborder: 1px solid black;\r\n");
      out.write("    \ttext-align: center;\r\n");
      out.write("    \tfont-weight: bold;\r\n");
      out.write("  \t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	out.println("<div align=\"center\">");
	out.println("<table class=\"cal\">");
	out.println("<tr class=\"cal\">");
		out.println("<td class=\"cal\"><font color=\"red\">일</font></td>");
		out.println("<td class=\"cal\">월</td>");
		out.println("<td class=\"cal\">화</td>");
		out.println("<td class=\"cal\">수</td>");
		out.println("<td class=\"cal\">목</td>");
		out.println("<td class=\"cal\">금</td>");
		out.println("<td class=\"cal\"><font color=\"blue\">토</font></td>");
	out.println("</tr>");
	for(int i = 0; i < 4; i++){
		out.println("<tr class=\"cal\">");
		for(int j = 0; j < 7; j++){
			out.println("<td class=\"cal\">&nbsp;</td>");
		}
		out.println("</tr>");
	}
	out.println("</table>");
	out.println("</div>");

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("</td>\r\n");
      out.write("\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t<td>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("\t<h1>오늘의 공지사항</h1>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t<li style=\"text-align: left;\">차년도 약학대학 입학전형 기본계획 공지</li>\r\n");
      out.write("\t<li style=\"text-align: left;\">차년도 정시모집 원서접수 현황</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>");
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
